title: Human-Autonomous Vehicle Interaction Workshop
email: zxz064@student.bham.ac.uk
description: Human-Autonomous Vehicle Interaction Workshop Series
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
google_analytics: UA-99765598-4

